version: '3.4'

networks:
  announcenetwork:

services:
  announce.db:
    image: mcr.microsoft.com/mssql/server
    ports: 
        - 1400:1433
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password1!
    networks:
        - announcenetwork
  announce.api:
    image: ${DOCKER_REGISTRY-}announceapi
    build:
      context: .
      dockerfile: Announce.Api/Dockerfile
    depends_on:
        - announce.db
    networks:
        - announcenetwork
